version: '3.8'

services:
  gateway-development:
    container_name: gateway-development
    restart: unless-stopped
    env_file: .env
    build:
      target: dev
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT:-3000}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
      - "9229:9229"
    volumes:
      - ./src:/app/src
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "512m"
        reservations:
          cpus: "0.25"
          memory: "256m"
